### ISSUE TITLE
SyntaxError in Python 3.7

### ISSUE THREAD

**Issue by pluto-the-lost** [saezlab/liana-py#12]
I used pip to install LIANA, the installation went smoothly. However, when import it shows

```
Traceback (most recent call last):

  File "/opt/miniconda3/envs/python37/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_2999548/1757714486.py", line 1, in <module>
    import liana as li

  File "/opt/miniconda3/envs/python37/lib/python3.7/site-packages/liana/__init__.py", line 4, in <module>
    from liana import method as mt, plotting as pl, resource as rs, utils as ut, multi as mu, funcomics as fun

  File "/opt/miniconda3/envs/python37/lib/python3.7/site-packages/liana/method/__init__.py", line 1, in <module>
    from ._Method import Method, MethodMeta, _show_methods

  File "/opt/miniconda3/envs/python37/lib/python3.7/site-packages/liana/method/_Method.py", line 133
    for sample in (progress_bar := tqdm(samples, disable=not verbose)):
                                ^
SyntaxError: invalid syntax
```

I believe the error show up because the operation ":=" is not added into python until 3.8. I created another environment with python 3.8, the problem was solved. Can you fix this to make Liana suitable for 3.7?

**Comment by dbdimitrov** [comment]
Hi,

This is related with a Python versioning issue, installing liana from github on Python3.7 would resolve it :)

https://github.com/saezlab/liana-py/issues/10

**Comment by dbdimitrov** [comment]
This will also be resolved on next pip release.
