### ISSUE TITLE
Numpy 1.24.x compatibility

### ISSUE THREAD

**Issue by DriesSchaumont** [saezlab/liana-py#24]
**Describe the bug**
Lianapy is incompatible with numpy 1.24.x because "float" is no longer importable

With numpy version 1.23.5
```
0.40 of entities in the resource are missing from the data.
Generating ligand-receptor stats for 713 samples and 17467 features
Assuming that counts were `natural` log-normalized!
.venv/lib/python3.10/site-packages/liana/method/_liana_pipe.py:419: RuntimeWarning: overflow encountered in power
.venv/lib/python3.10/site-packages/liana/method/_liana_pipe.py:412: RuntimeWarning: invalid value encountered in subtract
venv/lib/python3.10/site-packages/liana/method/_liana_pipe.py:412: RuntimeWarning: invalid value encountered in subtract
Running CellPhoneDB
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1136.74it/s]
Running Connectome
Running log2FC
Running NATMI
Running SingleCellSignalR
Running CellChat
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 187.00it/s]
```

With version 1.24.x
```
0.40 of entities in the resource are missing from the data.
Generating ligand-receptor stats for 713 samples and 17467 features
Assuming that counts were `natural` log-normalized!
.venv/lib/python3.10/site-packages/liana/method/_liana_pipe.py:419: RuntimeWarning: overflow encountered in power
.venv/lib/python3.10/site-packages/liana/method/_liana_pipe.py:412: RuntimeWarning: invalid value encountered in subtract
.venv/lib/python3.10/site-packages/liana/method/_liana_pipe.py:412: RuntimeWarning: invalid value encountered in subtract
Running CellPhoneDB
Traceback (most recent call last):
  File "src/interpret/lianapy/script.py", line 63, in <module>
    main()
  File "script.py", line 41, in main
    liana.mt.rank_aggregate(
  File ".venv/lib/python3.10/site-packages/liana/method/sc/_rank_aggregate.py", line 139, in __call__
    liana_res = liana_pipe(adata=adata,
  File ".venv/lib/python3.10/site-packages/liana/method/_liana_pipe.py", line 185, in liana_pipe
    _run_method(lr_res=lr_res.copy(),
  File "venv/lib/python3.10/site-packages/liana/method/_liana_pipe.py", line 462, in _run_method
    _get_means_perms(adata=adata,
  File "venv/lib/python3.10/site-packages/liana/method/_pipe_utils/_get_mean_perms.py", line 49, in _get_means_perms
    if isinstance(norm_factor, np.float):
  File ".venv/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

**To Reproduce**
If possible please provide a minimal reproducible example.
Unfortunatly, I am not able to send any data. However, I think this bug can be reproduced by using any random anndata file as long as version of numpy is 1.24.0 or older.

**Comment by dbdimitrov** [comment]
Hi @DriesSchaumont, 

Thanks for opening an issue & a PR, I have now merged it. I hope the issue is now resolved.

**Comment by DriesSchaumont** [comment]
@dbdimitrov That fixed it, thanks!
